version: '3.7'
services:
  mongo:
    image: mongo:4.0.20@sha256:dd4cbe24eb8233db92b871cc556b77efcc7f9e67bc9516579796d4d08818273e
    networks:
      kodify-technical-test:
        aliases:
          - mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data_db:/data/db
      - mongo_data_config_db:/data/configdb

  client:
    build:
      context: ./packages/client
      dockerfile: ./docker/env/artifacts/client/Dockerfile
    image: kodify-technical-test-client:latest
    networks:
      kodify-technical-test:
    ports:
      - 9227:9229
      - 30001:30000
    volumes:
      - .:/srv
      - node_modules_kodify-technical-test-client:/srv/packages/client/node_modules

  server:
    build:
      context: ./packages/server
      dockerfile: ./docker/env/artifacts/server/Dockerfile
    image: kodify-technical-test-server:latest
    networks:
      kodify-technical-test:
    ports:
      - 9228:9229
      - 30002:80
    volumes:
      - .:/srv
      - node_modules_kodify-technical-test-server:/srv/packages/server/node_modules

volumes:
  node_modules_kodify-technical-test-client:
  node_modules_kodify-technical-test-server:
  mongo_data_db:
  mongo_data_config_db:

networks:
  kodify-technical-test: